### PR TITLE
Fix imports for Python2 and Python3

### PR DESCRIPTION
**Pull request by alexvasiu**
I found a unique way that imports will work on Python2 and also on Python3.
Signed-off-by: Alexandru Vasiu <alexandru.vasiu@ni.com>

### CODE REVIEW

**Comment by bat-serjo** [comment]
Feel free to build and upload 0.0.4
I updated the setup.py but you'll have to re-update it to reflect py2

**Comment by alexvasiu** [comment]
@bat-serjo Yep, but I think I should build as 0.0.3 and update the package in pip because if I'll create 0.0.4 version, 0.0.3 will remain in pip and it's a version that doesn't work because of these import errors.

**Comment by bat-serjo** [comment]
No, put 0.0.4 and remove 0.0.3 so that it is no longer served.
If you replace 0.0.3 some user might have the old 0.0.3 version and he
won't know how to upgrade to the new one.

2018-03-07 22:26 GMT+02:00 Vasiu Alexandru <notifications@github.com>:

**Comment by alexvasiu** [comment]
Ok, I'll do like that ;) also to match py2 and py3, python_requires should be `>=2`.

**Comment by bat-serjo** [comment]
True it should.

2018-03-08 0:00 GMT+02:00 Vasiu Alexandru <notifications@github.com>:

**Comment by bat-serjo** [comment]
But make it >=2.7 cause i think there are syntax problems with older py2
versions.

2018-03-08 11:16 GMT+02:00 Sergei Kostov <bat.serjo@gmail.com>:

**Comment by alexvasiu** [comment]
@bat-serjo Ok. Can you please merge this into master?

**Pull request merged**
