### PR TITLE
Make compatible with Python3

### PR DESCRIPTION
**Pull request by alexvasiu**
Make compatible with Python3

Signed-off-by: Alexandru Vasiu <alexandru.vasiu@ni.com>

### CODE REVIEW

**Comment by bat-serjo** [comment]
Enjoy! 
Any ideas? Remarks?

**Comment by alexvasiu** [comment]
@bat-serjo Thank you :D Can I update this package on pip to include this python 3 compatibility or do I need some special permissions?

**Comment by bat-serjo** [comment]
Oh I forgot about that. I think you need my account there. I'll check if
you can be added as publisher too.

2018-03-05 18:49 GMT+02:00 Vasiu Alexandru <notifications@github.com>:

**Comment by alexvasiu** [comment]
If it's possible, my username on pypi.python.org/ is `avasiu` and email `alexandru.vasiu@ni.com`. Thank you :+1:

**Comment by bat-serjo** [comment]
Aiee, you're added. Do not speculate!

2018-03-06 12:56 GMT+02:00 Vasiu Alexandru <notifications@github.com>:

**Pull request merged**
